# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xsoda/code/relay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xsoda/code/relay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	cd /home/xsoda/code/relay && $(CMAKE_COMMAND) -E cmake_progress_start /home/xsoda/code/relay/CMakeFiles /home/xsoda/code/relay/deps/cbor/CMakeFiles/progress.marks
	cd /home/xsoda/code/relay && $(MAKE) -f CMakeFiles/Makefile2 deps/cbor/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xsoda/code/relay/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/xsoda/code/relay && $(MAKE) -f CMakeFiles/Makefile2 deps/cbor/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/xsoda/code/relay && $(MAKE) -f CMakeFiles/Makefile2 deps/cbor/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/xsoda/code/relay && $(MAKE) -f CMakeFiles/Makefile2 deps/cbor/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/xsoda/code/relay && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
deps/cbor/CMakeFiles/cbor.dir/rule:
	cd /home/xsoda/code/relay && $(MAKE) -f CMakeFiles/Makefile2 deps/cbor/CMakeFiles/cbor.dir/rule
.PHONY : deps/cbor/CMakeFiles/cbor.dir/rule

# Convenience name for target.
cbor: deps/cbor/CMakeFiles/cbor.dir/rule

.PHONY : cbor

# fast build rule for target.
cbor/fast:
	cd /home/xsoda/code/relay && $(MAKE) -f deps/cbor/CMakeFiles/cbor.dir/build.make deps/cbor/CMakeFiles/cbor.dir/build
.PHONY : cbor/fast

cbor.o: cbor.c.o

.PHONY : cbor.o

# target to build an object file
cbor.c.o:
	cd /home/xsoda/code/relay && $(MAKE) -f deps/cbor/CMakeFiles/cbor.dir/build.make deps/cbor/CMakeFiles/cbor.dir/cbor.c.o
.PHONY : cbor.c.o

cbor.i: cbor.c.i

.PHONY : cbor.i

# target to preprocess a source file
cbor.c.i:
	cd /home/xsoda/code/relay && $(MAKE) -f deps/cbor/CMakeFiles/cbor.dir/build.make deps/cbor/CMakeFiles/cbor.dir/cbor.c.i
.PHONY : cbor.c.i

cbor.s: cbor.c.s

.PHONY : cbor.s

# target to generate assembly for a file
cbor.c.s:
	cd /home/xsoda/code/relay && $(MAKE) -f deps/cbor/CMakeFiles/cbor.dir/build.make deps/cbor/CMakeFiles/cbor.dir/cbor.c.s
.PHONY : cbor.c.s

json.o: json.c.o

.PHONY : json.o

# target to build an object file
json.c.o:
	cd /home/xsoda/code/relay && $(MAKE) -f deps/cbor/CMakeFiles/cbor.dir/build.make deps/cbor/CMakeFiles/cbor.dir/json.c.o
.PHONY : json.c.o

json.i: json.c.i

.PHONY : json.i

# target to preprocess a source file
json.c.i:
	cd /home/xsoda/code/relay && $(MAKE) -f deps/cbor/CMakeFiles/cbor.dir/build.make deps/cbor/CMakeFiles/cbor.dir/json.c.i
.PHONY : json.c.i

json.s: json.c.s

.PHONY : json.s

# target to generate assembly for a file
json.c.s:
	cd /home/xsoda/code/relay && $(MAKE) -f deps/cbor/CMakeFiles/cbor.dir/build.make deps/cbor/CMakeFiles/cbor.dir/json.c.s
.PHONY : json.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... cbor"
	@echo "... cbor.o"
	@echo "... cbor.i"
	@echo "... cbor.s"
	@echo "... json.o"
	@echo "... json.i"
	@echo "... json.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/xsoda/code/relay && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

